# Generated by Django 2.2.2 on 2019-06-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_myuser'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='ServiceProviderID',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='id',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='userID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.myUser'),
            preserve_default=False,
        ),
    ]
