# Generated by Django 2.2.2 on 2019-06-17 19:36

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_myuser'),
        ('provider', '0004_auto_20190617_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='serviceprovider',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='id',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='userID',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='myuser_ptr',
            field=models.OneToOneField(auto_created=True, default=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.myUser'),
            preserve_default=False,
        ),
    ]
