# Generated by Django 2.2.2 on 2019-06-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20190617_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='userID',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
