# Generated by Django 2.2.2 on 2019-06-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20190619_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.myUser'),
        ),
    ]
