# Generated by Django 2.2.2 on 2019-06-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190615_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_provider',
            field=models.BooleanField(default=False, verbose_name='provider'),
        ),
    ]
