# Generated by Django 2.2.2 on 2019-06-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_is_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='securityquestion1',
            field=models.CharField(default=True, max_length=20, verbose_name='Security question 1: What is the name of hospital were you born in?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='securityquestion2',
            field=models.CharField(default=True, max_length=20, verbose_name='Securtiy question 2: What was your childhood friends name?'),
            preserve_default=False,
        ),
    ]
