# Generated by Django 2.2.2 on 2019-06-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190615_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
